services:
  - type: web
    name: django-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    plan: free
    build:
      dockerfilePath: Dockerfile.web
    routes:
      - type: primary
        name: "web"
        path: /
        port: 8000

  - type: worker
    name: celery-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A config worker --loglevel=info"
    plan: free
    build:
      dockerfilePath: Dockerfile.celery
