services:
  - type: web
    name: django-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "supervisord -c /etc/supervisor/conf.d/supervisord.conf"
    plan: free
    build:
      dockerfilePath: Dockerfile
    routes:
      - type: primary
        name: "web"
        path: /
        port: 8000
