services:
  - type: web
    name: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    plan: free
    build:
      dockerfilePath: Dockerfile
    routes:
      - type: primary
        name: "web"
        path: /
        port: 8000

  - type: worker
    name: celery
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A config worker --loglevel=info"
    plan: free
    build:
      dockerfilePath: Dockerfile

  - type: redis
    name: redis
    plan: free

  - type: database
    name: postgres
    plan: free
    database:
      engine: postgres
      version: "13"
      username: tanmya_hr_user
      password: vJzviMz46OSrHVoV0cjTZ9tMRxP4h8Lv
      database: tanmya_hr
